"""add_duplicate_relations

Revision ID: 735b7119c26f
Revises: ca19841fee03
Create Date: 2026-07-16 04:08:39.266438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '735b7119c26f'
down_revision: Union[str, Sequence[str], None] = 'ca19841fee03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duplicate_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('duplicate_of_item_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.Enum('exact_external_id', 'exact_canonical_url', 'exact_content_hash', 'same_source_title', 'cross_source_story', 'manual', name='relationtype'), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('review_status', sa.Enum('auto_confirmed', 'pending_review', 'confirmed', 'rejected', name='reviewstatus'), nullable=False),
    sa.CheckConstraint('item_id != duplicate_of_item_id', name='chk_no_self_duplicate'),
    sa.ForeignKeyConstraint(['duplicate_of_item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'duplicate_of_item_id', 'relation_type', name='uq_item_duplicate_relation')
    )
    op.create_index('ix_duplicate_relations_duplicate_of_item_id', 'duplicate_relations', ['duplicate_of_item_id'], unique=False)
    op.create_index('ix_duplicate_relations_item_id', 'duplicate_relations', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_duplicate_relations_item_id', table_name='duplicate_relations')
    op.drop_index('ix_duplicate_relations_duplicate_of_item_id', table_name='duplicate_relations')
    op.drop_table('duplicate_relations')
    # ### end Alembic commands ###
