"""initial

Revision ID: ca19841fee03
Revises: 
Create Date: 2026-07-16 03:43:08.737380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca19841fee03'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collector_name', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('items_found', sa.Integer(), nullable=False),
    sa.Column('items_created', sa.Integer(), nullable=False),
    sa.Column('items_skipped', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('trust_level', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('canonical_url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('collected', 'normalized', 'duplicate', 'pending_analysis', 'analyzed', 'rejected', 'pending_review', 'approved', 'published', 'failed', name='itemstatus'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_index('ix_items_canonical_url', 'items', ['canonical_url'], unique=False)
    op.create_index('ix_items_published_at', 'items', ['published_at'], unique=False)
    op.create_index('ix_items_source_id', 'items', ['source_id'], unique=False)
    op.create_index('ix_items_status', 'items', ['status'], unique=False)
    op.create_table('item_analysis',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('news', 'model_release', 'local_model', 'agent', 'coding_agent', 'agent_harness', 'skill', 'prompt', 'mcp_server', 'framework', 'research', 'dataset', 'benchmark', 'api', 'tutorial', 'security', 'funding', 'opinion', 'other', name='categoryenum'), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary_ru', sa.Text(), nullable=False),
    sa.Column('what_is_new', sa.Text(), nullable=True),
    sa.Column('why_important', sa.Text(), nullable=True),
    sa.Column('practical_use', sa.Text(), nullable=True),
    sa.Column('target_users', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_primary_source', sa.Boolean(), nullable=False),
    sa.Column('is_promotional', sa.Boolean(), nullable=False),
    sa.Column('novelty_score', sa.Integer(), nullable=True),
    sa.Column('practicality_score', sa.Integer(), nullable=True),
    sa.Column('credibility_score', sa.Integer(), nullable=True),
    sa.Column('relevance_score', sa.Integer(), nullable=True),
    sa.Column('popularity_score', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('raw_llm_response', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('publications',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('telegram_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_review', 'approved', 'rejected', 'published', 'failed', name='publicationstatus'), nullable=False),
    sa.Column('moderation_chat_id', sa.Integer(), nullable=True),
    sa.Column('moderation_message_id', sa.Integer(), nullable=True),
    sa.Column('telegram_channel_id', sa.Integer(), nullable=True),
    sa.Column('telegram_message_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publications')
    op.drop_table('item_analysis')
    op.drop_index('ix_items_status', table_name='items')
    op.drop_index('ix_items_source_id', table_name='items')
    op.drop_index('ix_items_published_at', table_name='items')
    op.drop_index('ix_items_canonical_url', table_name='items')
    op.drop_table('items')
    op.drop_table('sources')
    op.drop_table('collection_runs')
    # ### end Alembic commands ###
